export const FETCH_GROUPS_SUCCESS='FETCH_GROUPS_SUCCESS'
export const FETCH_GROUPS_ERROR='FETCH_GROUPS_ERROR'

export const FETCH_PRODUCTS_SUCCESS='FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR='FETCH_PRODUCTS'

export const FETCH_PRODUCT_ID_SUCCESS='FETCH_PRODUCT_ID_SUCCESS'
export const FETCH_PRODUCT_ID_ERROR='FETCH_PRODUCT_ID_ERROR'

export const ADD_CART = 'ADD_CART'
export const DELETE_CART = 'DELETE_CART'
export const FETCH_CARTS='FETCH_CARTS'
export const NEW_CART='NEW_CART'

export const FETCH_ROLES_SUCCESS='FETCH_ROLES_SUCCESS'
export const FETCH_ROLES_ERROR='FETCH_ROLES'


export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR= 'EDIT_USER_ERROR'
export const NEW_USER='NEW_USER'
export const CLEAR_USERS='CLEAR_USERS'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAILED='LOGOUT_FAILED'


export const ADD_TRANSACTION_HEADER_SUCCESS = 'ADD_TRANSACTION_HEADER_SUCCESS'
export const ADD_TRANSACTION_HEADER_ERROR = 'ADD_TRANSACTION_HEADER_ERROR'
export const FETCH_TRANSACTION_HEADERS_SUCCESS='FETCH_TRANSACTION_HEADERS_SUCCESS'
export const FETCH_TRANSACTION_HEADERS_ERROR='FETCH_TRANSACTION_HEADERS'
export const EDIT_TRANSACTION_HEADER_SUCCESS = 'EDIT_TRANSACTION_HEADER_SUCCESS'
export const EDIT_TRANSACTION_HEADER_ERROR = 'EDIT_TRANSACTION_HEADER_ERROR'
export const FETCH_TRANSACTION_HEADERS_USER_SUCCESS='FETCH_TRANSACTION_HEADERS_USER_SUCCESS'
export const FETCH_TRANSACTION_HEADERS_USER_ERROR='FETCH_TRANSACTION_HEADERS_USER_ERROR'
export const NEW_TRANSACTION_HEADER='NEW_TRANSACTION_HEADER'
export const CLEAR_TRANSACTION_HEADERS='CLEAR_TRANSACTION_HEADERS'
export const FETCH_TRANSACTION_HEADERS='FETCH_TRANSACTION_HEADERS'

export const ADD_TRANSACTION_DETAIL_SUCCESS = 'ADD_TRANSACTION_DETAIL_SUCCESS'
export const ADD_TRANSACTION_DETAIL_ERROR = 'ADD_TRANSACTION_DETAIL_ERROR'
export const CLEAR_TRANSACTION_DETAILS='CLEAR_TRANSACTION_DETAILS'
export const FETCH_TRANSACTION_DETAIL_ID_SUCCESS='FETCH_TRANSACTION_DETAIL_ID_SUCCESS'
export const FETCH_TRANSACTION_DETAIL_ID_ERROR='FETCH_TRANSACTION_DETAIL_ID_ERROR'
export const NEW_TRANSACTION_DETAIL='NEW_TRANSACTION_DETAIL'
export const CLEAR_TRANSACTION_DETAILS='CLEAR_TRANSACTION_DETAILS'

export const ADD_HISTORY_SUCCESS = 'ADD_HISTORY_SUCCESS'
export const ADD_HISTORY_ERROR = 'ADD_HISTORY_ERROR'
export const NEW_HISTORY='NEW_HISTORY'


export const ROOT_URL = 'http://localhost:3010/api';
export const IMAGE_URL='http://localhost:3010/static';
